Repository retaildevcrews/gh-template, pull requests merged in 2020-09, with the labels that each got.

#2 Added docs folder to fix dead link
  docs/EngineeringPractices.md
Labels: Bug, Documentation

#3 updated from CPR feedback
  .github/ISSUE_TEMPLATE/release.md
  docs/EngineeringPractices.md
Labels: Documentation

#7 Create Sprint0
  .github/ISSUE_TEMPLATE/Sprint0
Labels: Process

#6 Create EngineeringFundChecklist.md
  .github/ISSUE_TEMPLATE/EngineeringFundChecklist.md
Labels: Process

#5 Update checkpoint.md
  .github/ISSUE_TEMPLATE/checkpoint.md
Labels: CPR, Documentation
